### ISSUE TITLE
insyde H20SDE Readonly mode？

### ISSUE THREAD

**Issue by wangxiaodiao** [chinese-opendesktop/repo-bin#1]
insyde H20SDE运行出现Readonly mode，无法修改dmi信息

**Comment by bluebat** [comment]
確認是 Insyde BIOS?
是否仍然可以手動變更 BIOS 設定值？

**Comment by bluebat** [comment]
是否以 root 身分執行？
BIOS 是否有設定密碼？

**Comment by wangxiaodiao** [comment]
是root用户运行，bios未设定密码

**Comment by bluebat** [comment]
我衹進行製作 RPM，技術問題可能幫不上忙了。

**Comment by wangxiaodiao** [comment]
请问一下，你运行insyde H20SDE可以修改dmi信息吗？是否为只读呢？

**Comment by bluebat** [comment]
於內核 4.14.13 測試了一下(改善一個編譯錯誤)，是可以修改 DMI 的。

**Comment by wangxiaodiao** [comment]
和内核版本有关系吗？我的是centos 7.4，内核版本是3.10

**Comment by bluebat** [comment]
沒試過，也許用舊版本的工具看看。

**Comment by wangxiaodiao** [comment]
旧版本linux工具吗？我这里只有windows 工具，windows的insyde H20FFT工具能修改dmi信息，并且能够修改成功，但是重启后修改的内容又还原了

**Comment by bluebat** [comment]
確定可以手動修改 BIOS 而不是最近發生的 intel_spi 鎖住 BIOS 問題嗎？

**Comment by wangxiaodiao** [comment]
可以手动修改bios的，应该不是因为intel_spi导致的，怎么确定是intel_spi导致的呢？

**Comment by bluebat** [comment]
如果可以手動修改且重啟後內容確實有變更，那就不是 intel_spi 的問題了。

**Comment by wangxiaodiao** [comment]
那请问一下，这个问题是什么原因呢？这个问题困扰我很久，一直不知道怎么解决？我能发一份bios给你，你帮我看一下吗？

**Comment by bluebat** [comment]
不太方便，請詢問 Insyde 較適合。

**Comment by wangxiaodiao** [comment]
好吧
